# Generated by Django 5.2.9 on 2026-01-08 05:03

import campaign.models
import campaign.storage_backends
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('organization', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('message', models.TextField(help_text='Campaign message content')),
                ('campaign_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='draft', max_length=25)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('emails_delivered', models.PositiveIntegerField(default=0)),
                ('emails_opened', models.PositiveIntegerField(default=0)),
                ('emails_clicked', models.PositiveIntegerField(default=0)),
                ('emails_bounced', models.PositiveIntegerField(default=0)),
                ('emails_failed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, help_text='List of attachments (base64 or URLs)', null=True)),
                ('components', models.JSONField(blank=True, help_text='Email builder components JSON', null=True)),
                ('design_started', models.BooleanField(default=False, help_text='Has the design/editor been started?')),
                ('design_source', models.CharField(blank=True, default='', help_text="'scratch' or 'template'", max_length=20)),
                ('rendered_html', models.TextField(blank=True, default='', help_text='Cached rendered HTML (without personalization)')),
                ('html_generated_at', models.DateTimeField(blank=True, help_text='When HTML was last generated', null=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('organization', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.ImageField(blank=True, null=True, storage=campaign.storage_backends.PublicMediaStorage(), upload_to=campaign.models.campaign_image_upload_path)),
                ('source_url', models.URLField(blank=True, default='')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign Image',
                'verbose_name_plural': 'Campaign Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEmailFooterSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('custom_html', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Email Footer Settings',
                'verbose_name_plural': 'User Email Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_email', models.EmailField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('email_opened_at', models.DateTimeField(blank=True, null=True)),
                ('email_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('email_bounced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaign.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Recipient',
                'verbose_name_plural': 'Campaign Recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='resend', max_length=50)),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(default='sent', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaign.campaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaign.campaignrecipient')),
            ],
            options={
                'verbose_name': 'Campaign Message',
                'verbose_name_plural': 'Campaign Messages',
            },
        ),
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsubscribes', to='campaign.campaign')),
            ],
            options={
                'verbose_name': 'Email Unsubscribe',
                'verbose_name_plural': 'Email Unsubscribes',
            },
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='cr_campaign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['email'], name='cr_email_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['status', 'created_at'], name='cr_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmessage',
            index=models.Index(fields=['message_id'], name='campaign_ca_message_e49d41_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmessage',
            index=models.Index(fields=['campaign', 'recipient'], name='campaign_ca_campaig_fe5728_idx'),
        ),
        migrations.AddIndex(
            model_name='emailunsubscribe',
            index=models.Index(fields=['user_email', 'email'], name='campaign_em_user_em_0a9c03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailunsubscribe',
            unique_together={('user_email', 'email')},
        ),
    ]
