# Generated by Django 5.2.9 on 2026-01-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='person_email',
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='person_id',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
