# Generated by Django 5.2.9 on 2026-01-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_remove_campaign_user_campaign_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='useremailfootersettings',
            name='user',
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='user_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='person_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useremailfootersettings',
            name='user_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
